name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-12-xl
    env:
      TF_CPP_MIN_LOG_LEVEL: 3
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: install brew on mac
        run: |
          brew install sbt
      - name: Run tests
        run: sbt test
